<a href="https://colab.research.google.com/github/kimjaehwankimjaehwan/deeplearningstudy/blob/main/03_Pandas%EC%98%88%EC%A0%9C_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0. 아파트 실거래가 데이터 활용

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/data/trade_apt_api.csv')

In [ ]:
df.head(3)

,기준년월,지역명,지역코드,법정동,아파트,거래금액,년,월,일,건축년도,전용면적,층
0,202006,서울특별시종로구,11110,신교동,신현(102동),100000,2020,6,30,2002,134.66,5
1,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),121500,2020,6,4,2008,126.34,7
2,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),115000,2020,6,9,2008,94.28,5

1. 아파트 실거래가 데이터를 활용하여 각 동별, 아파트별 평균 거래가를 구하고, 거래금액이 가장 높은 순서로 정렬하여 출력. 가장 높은 평균거래가와 가장 낮은 평균거래가의 차이를 구한 후 출력

*  법정동과 아파트를 기준으로 각 평균값을 구함

<ipython-input-5-7d9f1ec31dfe>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_grp = df.groupby(['법정동', '아파트'], as_index=False).mean()

,법정동,아파트,기준년월,지역코드,거래금액,년,월,일,건축년도,전용면적,층
0,교북동,동아,202006.0,11110.0,62000.0,2020.0,6.0,16.0,1995.0,59.980000,10.000000
1,구기동,마운틴뷰,202006.0,11110.0,40000.0,2020.0,6.0,12.0,2019.0,76.660000,1.000000
2,내수동,경희궁의아침2단지,202006.0,11110.0,155000.0,2020.0,6.0,11.5,2004.0,149.360000,7.000000
3,내수동,경희궁의아침3단지,202006.0,11110.0,168500.0,2020.0,6.0,10.0,2004.0,166.033333,10.666667
4,내수동,세종로대우,202006.0,11110.0,95000.0,2020.0,6.0,5.0,1994.0,109.910000,11.000000

*  이 데이터를 거래금액이 많은 순으로 정렬

,법정동,아파트,기준년월,지역코드,거래금액,년,월,일,건축년도,전용면적,층
3,내수동,경희궁의아침3단지,202006.0,11110.0,168500.0,2020.0,6.0,10.0,2004.0,166.033333,10.666667
37,홍파동,경희궁자이(2단지),202006.0,11110.0,161500.0,2020.0,6.0,24.4,2017.0,81.685300,9.600000
5,내수동,킹스매너,202006.0,11110.0,158000.0,2020.0,6.0,16.0,2004.0,218.860000,2.000000
2,내수동,경희궁의아침2단지,202006.0,11110.0,155000.0,2020.0,6.0,11.5,2004.0,149.360000,7.000000
33,평동,경희궁자이(3단지),202006.0,11110.0,151500.0,2020.0,6.0,17.4,2017.0,69.847400,5.600000

*  이 데이터 첫 행의 거래금액값과 마지막 행의 거래금액값을 추출한 후 차이를 계산하고 출력

168500.0 11200.0 157300.0

* head, tail을 사용하지 않고 df.loc를 사용

168500.0 11200.0 157300.0

2. 저층(1층~3층) 아파트가격 비율이 가장 낮은 법정동을 찾아 구매하고자 하는데, 건축한지 2010년 이전에 지은 아파트에는 입주하고 싶지 않아 제외합니다. 어떤 법정동의 어떤 아파트를 추천할 것인지와 해당 아파트의 저층 가격 비율을 함께 출력.

* 법정동을 기준으로 그루핑하여 거래금액 평균가를 구함

<ipython-input-9-e5307ee89d3d>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_grp = df.groupby("법정동").mean()['거래금액']

법정동
교북동     62000.000000
구기동     40000.000000
내수동    152642.857143
Name: 거래금액, dtype: float64

* 3층 이하로 필터링한 후 법정동을 기준으로 그루핑하여 저층의 거래금액 평균가를 구함

<ipython-input-10-c3f6093c943e>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_low_grp = df_low.groupby("법정동").mean()['거래금액']

법정동
구기동     40000.0
내수동    158000.0
무악동     77000.0
Name: 거래금액, dtype: float64

* 각 동별 전체층의 평균가와 저층의 평균가 데이터를 합치고(pd.concat) 열이름을 각각 '전체층', '저층'으로 수정

               전체층        저층
법정동
교북동   62000.000000       NaN
구기동   40000.000000   40000.0
내수동  152642.857143  158000.0

* 저층 평균거래가격 / 전체층 평균거래가격을 계산하여 '저층거래가격비율'이라는 열에 입력

               전체층        저층   저층거래가비율
법정동
교북동   62000.000000       NaN       NaN
구기동   40000.000000   40000.0  1.000000
내수동  152642.857143  158000.0  1.035096

* 비율이 낮은 순으로 정렬한 후 가장 낮은 값의 '법정동'명을 구함(df.index)

('무악동', 0.7443434129837175)

* 전체 데이터 중에서 법정동이 위에서 구한 동명이고, 건축년도가 2010초과인 경우를 필터링하여 결과값을 구함

저층가격비율이 74.4%인 무악동의 무악다온채아파트를 추천합니다.

3. 1일-15일, 16일-마지막날까지로 2개의 기간을 구분하여 거래 평균가격 증감율이 많이 큰 법정동 3곳을 구한 후, 이 3곳 중 16일~마지막날까지 가장 많은 거래량을 보인 법정동 1곳을 관리 지역으로 지정하려고 할 때 어디를 지정하는 것이 타당한지 구한 후 출력

* 1일부터 15일까지의 거래를 df1로 생성

,기준년월,지역명,지역코드,법정동,아파트,거래금액,년,월,일,건축년도,전용면적,층
1,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),121500,2020,6,4,2008,126.34,7
2,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),115000,2020,6,9,2008,94.28,5
3,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),113000,2020,6,13,2008,97.61,1

* 16일부터 말일까지의 거래를 df2로 생성

,기준년월,지역명,지역코드,법정동,아파트,거래금액,년,월,일,건축년도,전용면적,층
0,202006,서울특별시종로구,11110,신교동,신현(102동),100000,2020,6,30,2002,134.66,5
4,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),124000,2020,6,16,2008,94.51,5
5,202006,서울특별시종로구,11110,사직동,광화문풍림스페이스본(101동~105동),120000,2020,6,20,2008,91.35,14

*  보름전의 법정동별 평균 거래금액을 구함

<ipython-input-17-6d07dbdebf00>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df1_grp = df1.groupby('법정동').mean().sort_values('거래금액', ascending=False)['거래금액']

법정동
홍파동     149500.000000
평동      141500.000000
내수동     140500.000000
사직동     116500.000000
무악동      90237.500000
명륜2가     89700.000000
평창동      79100.000000
당주동      79000.000000
인의동      71000.000000
숭인동      63614.285714
창신동      56294.444444
구기동      40000.000000
익선동      36000.000000
Name: 거래금액, dtype: float64

*  보름후의 법정동별 평균 거래금액을 구함

<ipython-input-18-8540fcbaa550>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2_grp = df2.groupby('법정동').mean().sort_values('거래금액', ascending=False)['거래금액']

법정동
내수동    168833.333333
홍파동    162833.333333
평동     154000.000000
사직동    129500.000000
무악동    107850.000000
신교동    100000.000000
인의동     92750.000000
평창동     78940.000000
교북동     62000.000000
창신동     57685.714286
익선동     47000.000000
숭인동     41300.000000
Name: 거래금액, dtype: float64

* 보름전 평균가격과 보름후 평균가격을 합친 후(pd.concat) 열 이름을 각각 '보름전', '보름후'로 바꾼 후 '증감'열을 생성하여 비율을 구함. 상위 3개동을 대상으로 추출

Index(['인의동', '익선동', '내수동'], dtype='object', name='법정동')

* 법정동별 거래 횟수 집계(count()) 데이터를 만든 후 위에서 구한 3개동에 해당하는 동의 거래금액을 추출(df[df.index.isin(some_list)])하고 정렬하여 가장 거래횟수가 많은 동을 출력

법정동
인의동    4
Name: 거래금액, dtype: int64

4. 정부가 아파트를 구입할 때는 지원금을 1억씩 준다고 한다. 그런데 전체 구매자에게 다 지원할 수 없기 때문에 지정 거래면적 이하인 경우만 지원하려고 한다. 전체 거래액 대비 구매자 부담 감소율을 5% 이상 낮추는 것을 정책의 목표로 삼고 있을 때, 몇 제곱미터 이하에게 지원금을 주는 것이 최소 예산으로 목표달성을 할 수 있는지 구한 후 출력

* 전용면적의 고유값(unique())을 구한 후 오름차순 정렬

array([ 12.78  ,  15.09  ,  17.96  ,  19.466 ,  28.8   ,  48.54  ,
        50.31  ,  54.7   ,  59.01  ,  59.3   ,  59.855 ,  59.92  ,
        59.94  ,  59.95  ,  59.98  ,  59.993 ,  60.    ,  64.66  ,
        76.66  ,  77.974 ,  79.87  ,  80.85  ,  83.83  ,  84.614 ,
        84.7   ,  84.82  ,  84.836 ,  84.858 ,  84.87  ,  84.9   ,
        84.907 ,  84.92  ,  84.944 ,  84.9478,  84.98  ,  84.99  ,
        91.35  ,  94.28  ,  94.51  ,  97.61  ,  98.39  , 102.89  ,
       106.62  , 108.18  , 109.91  , 110.53  , 110.61  , 114.67  ,
       114.9   , 114.931 , 115.53  , 124.17  , 126.34  , 133.34  ,
       134.66  , 149.    , 150.4   , 169.86  , 174.55  , 200.19  ,
       218.86  ])

* 정책 시행 전의 거래금액 합계를 구해 둔다.

10637450

* 정책 시행 후 변경된 거래금액의 비율을 구하는 함수를 준비
    * 전용면적이 기준면적 이하인 경우에는 거래금액을 10000만큼 감소
    * 변경 후 거래금액 합계를 구함
    * 변경 후 거래금액의 감소 비율을 구함

* 정책 적용 후 데이터를 복제
* 반복문을 통해 각각의 전용면적별로 정책효과가 얼마나 나타나는지 계산
* 목표 비율인 5%이상 도달하면 반복문을 종료하고 해당 기준을 출력

12.78 0.0009400749239714123 10627450 10637450
15.09 0.002820224771914348 10607450 10637450
17.96 0.005640449543828696 10577450 10637450
19.466 0.009400749239714457 10537450 10637450
28.8 0.015981273707514454 10467450 10637450
48.54 0.023501873099285975 10387450 10637450
50.31 0.03196254741502902 10297450 10637450
54.7 0.04794382112254347 10127450 10637450
59.01 0.06486516975402945 9947450 10637450

면적 59.01이하를 지원할 때, 목표비율 6.486517%에 도달했습니다.